In [7]:
import pandas as pd
import scipy.stats as stats
import researchpy as rp
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [3]:

df=pd.read_csv('2_difi.csv')

In [2]:
df

NameError: name 'df' is not defined

In [4]:
df

    person  dose  libido
0        1     1       3
1        2     1       2
2        3     1       1
3        4     1       1
4        5     1       4
5        6     2       5
6        7     2       2
7        8     2       4
8        9     2       2
9       10     2       3
10      11     3       7
11      12     3       4
12      13     3       5
13      14     3       3
14      15     3       6

In [5]:
df['dose'].replace({1:'placebo',2:'low',3:'high'},inplace=True)

In [6]:
df

    person     dose  libido
0        1  placebo       3
1        2  placebo       2
2        3  placebo       1
3        4  placebo       1
4        5  placebo       4
5        6      low       5
6        7      low       2
7        8      low       4
8        9      low       2
9       10      low       3
10      11     high       7
11      12     high       4
12      13     high       5
13      14     high       3
14      15     high       6

In [8]:
#gettin summary statics 
rp.summary_cont(df['libido'])

  Variable     N      Mean       SD        SE  95% Conf.  Interval
0   libido  15.0  3.466667  1.76743  0.456349   2.487896  4.445437

In [9]:
rp.summary_cont(df['libido'].groupby(df['dose']))

         N  Mean        SD        SE  95% Conf.  Interval
dose
high     5   5.0  1.581139  0.707107   3.450484  6.549516
low      5   3.2  1.303840  0.583095   1.922236  4.477764
placebo  5   2.2  1.303840  0.583095   0.922236  3.477764

In [11]:
results = ols('libido ~ C(dose)',data=df).fit()
results.summary()

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=15
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 libido   R-squared:                       0.460
Model:                            OLS   Adj. R-squared:                  0.370
Method:                 Least Squares   F-statistic:                     5.119
Date:                Tue, 23 Jul 2019   Prob (F-statistic):             0.0247
Time:                        14:35:36   Log-Likelihood:                -24.683
No. Observations:                  15   AIC:                             55.37
Df Residuals:                      12   BIC:                             57.49
Df Model:                           2
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              5.0000      0.627      7.972      0.000       3.634       6.366
C(dose)[T.low]        -1.8000      0.887     -2.029      0.065      -3.732       0.132
C(dose)[T.placebo]    -2.8000      0.887     -3.157      0.008      -4.732      -0.868
==============================================================================
Omnibus:                        2.517   Durbin-Watson:                   2.408
Prob(Omnibus):                  0.284   Jarque-Bera (JB):                1.108
Skew:                           0.195   Prob(JB):                        0.575
Kurtosis:                       1.727   Cond. No.                         3.73
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""